[project]
name = "optimalinterp"
version = "0.1.0"
description = "Package for creating optimal interpolants"
readme = "README.md"
authors = [
    { name = "Daniel Sharp", email = "dannys4@mit.edu" },
    { name = "Panos Tsimpos", email = "ptsimpos@mit.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "chex>=0.1.91",
    "diffrax>=0.7.2",
    "equinox>=0.13.8",
    "jax>=0.8.1",
    "jaxtyping>=0.3.3",
    "matplotlib>=3.11.1",
    "numpy>=2.3.5",
    "optimistix>=0.1.0",
    "scipy>=1.16.3",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.1",
    "jupytext>=1.19.4",
    "pytest>=9.0.1",
]
